include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    prefer_relative_imports: true
    always_declare_return_types: true
    unnecessary_brace_in_string_interps: true
    prefer_interpolation_to_compose_strings: true
    prefer_final_fields: true
    directives_ordering: true
    curly_braces_in_flow_control_structures: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
