name: hackathon_app
description: A Flutter mobile app template optimized for hackathon projects.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  get: ^4.6.5
  
  # Storage
  hive: ^2.2.3
  shared_preferences: ^2.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Network
  shimmer: ^3.0.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.1
  
  # Utils
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # UI
  lottie: ^2.6.0
  flutter_spinkit: ^5.2.0
  
  # Form
  form_validator: ^2.1.1
  flutter_form_builder: ^9.1.0
  uuid: ^4.5.1

  # Uncomment dependencies as needed for your hackathon project:
  
  # ===== FIREBASE INTEGRATION =====
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6
  # firebase_storage: ^11.5.6
  # firebase_messaging: ^14.7.9
  # firebase_analytics: ^10.7.4
  
  # ===== LOCATION & MAPS =====
  # geolocator: ^10.1.0
  # geocoding: ^2.1.1
  # google_maps_flutter: ^2.5.0
  # flutter_map: ^6.0.1
  
  # ===== SOCIAL & SHARING =====
  # share_plus: ^7.2.1
  # flutter_social_content_share: ^1.0.2
  # flutter_facebook_auth: ^6.0.3
  # twitter_login: ^4.4.2
  # google_sign_in: ^6.1.6
  
  # ===== FILE HANDLING =====
  # file_picker: ^6.1.1
  # video_player: ^2.8.1
  # just_audio: ^0.9.36
  # pdf: ^3.10.6
  # flutter_pdfview: ^1.3.2
  
  # ===== MACHINE LEARNING =====
  # google_ml_kit: ^0.16.3
  # tflite_flutter: ^0.10.3
  # camera: ^0.10.5+5
  
  # ===== ADVANCED UI =====
  # flutter_staggered_animations: ^1.1.1
  # animations: ^2.0.8
  # fl_chart: ^0.64.0
  # syncfusion_flutter_charts: ^23.2.7
  # table_calendar: ^3.0.9
  # flutter_slidable: ^3.0.1
  
  # ===== OFFLINE & SYNC =====
  # connectivity_plus: ^5.0.2
  # sqflite: ^2.3.0
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  
  # ===== PAYMENT INTEGRATION =====
  # stripe_checkout: ^1.0.2
  # flutter_stripe: ^9.5.0+1
  # in_app_purchase: ^3.1.11
  
  # ===== AR/VR =====
  # arkit_plugin: ^1.0.7
  # ar_flutter_plugin: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
